server:
  port: 19064

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19041/eureka/

spring:
  application:
    name: service-author

  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: tianyikeji2017
    timeout: 5000
  profiles:
    active: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://@dbUrl@/@dbName@?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: @dbUser@
    password: @dbPassword@
    business:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://@dbBusiUrl@/@dbName@?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8
      username: @dbBusiUser@
      password: @dbBusiPassword@
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tianyi.datacenter.*.entity
tianyi:
  intesrv:
    url: http://smartuat.tygps.com
  tableau:
    url: http://192.168.88.130
    username: test
    target_site: TYAnalysis
    client_ip: 192.168.111.23

#jwt生成密钥
jwt:
  secret:
    key: asdfghjkl
  blacklist:
    key:
      format: JWT_BLACKLIST::%s
  refresh:
    token:
      key:
        format: JWT_REFRESH_TOKEN::%s
#refreshToken 存储key
token:
  expire:
    time: 3600000
#refreshToken过期时间：2min
refresh:
  token:
    expire:
      time: 120000


